name: Generate and Visualize Data Distribution

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and Test
        run: mvn clean install

      - name: Generate Random Data
        run: python generate_data.py
        env:
          MAVEN_CLI_OPTS: "-Dmaven.repo.local=$HOME/.m2/repository"

      - name: Visualize Data Distribution
        run: python visualize_distribution.py

