name: Maven Build, Test, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: Copy Maven settings.xml
        run: cp .github/setting.xml $HOME/.m2/settings.xml
        
      - name: Build
        run: mvn -B package --file pom.xml

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: Copy Maven settings.xml
        run: cp .github/setting.xml $HOME/.m2/settings.xml

      - name: Test
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: Copy Maven settings.xml
        run: cp .github/setting.xml $HOME/.m2/settings.xml

      - name: Deploy
        run: mvn deploy
