name: Maven Build, Test, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout branch from Github
        uses: actions/checkout@v3
      - name: Set up JDK 170-
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          cache: maven
      - name: Build gpsUtil with Maven
        run: mvn install:install-file -Dfile=/home/runner/work/Projet8TourGuide/TourGuide/libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
      - name: Build reward central with Maven
        run: mvn install:install-file -Dfile=/home/runner/work/Projet8TourGuide/TourGuide/libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
      - name: Build tripPricer with Maven
        run: mvn install:install-file -Dfile=/home/runner/work/Projet8TourGuide/TourGuide/libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
      - name: Clean
        run: |
          cd /home/runner/work/Projet8TourGuide/TourGuide/
          mvn clean
      - name: compilation
        run: |
          cd /home/runner/work/Projet8TourGuide/TourGuide/
          mvn compile
      - name: test
        run: |
          cd /home/runner/work/Projet8TourGuide/TourGuide/
          mvn test
      - name: update artefact
        run:  |
          cd /home/runner/work/Projet8TourGuide/TourGuide/
          mvn --batch-mode --update-snapshots install -DskipTests
      - name: create package
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: /home/runner/.m2/repository/com/openclassrooms/tourguide/0.0.1-SNAPSHOT/